services:
    blog.tokens.action_listener:
        class: B2B\BlogBundle\EventListener\TokenListener
        arguments: [@service_container, @request_stack]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    buzz.curl:
        class: B2B\BlogBundle\Services\Curl
        arguments: [@service_container, @request_stack]
